
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: lokeshDB
      MYSQL_PASSWORD: lokes123
      MYSQL_ROOT_PASSWORD: lokesh123
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - 3307:3306
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: